;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beatp-delete-left-to-boundary
        beatp-delete-right-to-boundary
        beatp-dwim-kill
        beatp-dwim-previous-line
        beatp-dwim-save
        beatp-left-to-boundary
        beatp-right-to-boundary
        beginning-of-defun
        c-electric-brace
        c-electric-paren
        electric-pair-delete-pair
        end-of-defun
        eros-eval-last-sexp
        haskell-indentation-common-electric-command
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        killer-yank
        lsp-ui-doc--handle-mouse-movement
        promela-open-delimiter
        ryanmarcus/backward-kill-word
        shit
        tab-region
        untab-region
        ))

(setq mc/cmds-to-run-once
      '(
        beatp-select-around-word-or-next-match
        beatp-select-word-or-next-match
        consult-buffer
        consult-line-dwim
        corfu--mc--insert
        corfu-complete
        corfu-insert
        corfu-next
        corfu-previous
        corfu-quit
        corfu-test
        counsel-M-x
        describe-key
        describe-keymap
        eglot
        handle-switch-frame
        make
        markdown-outdent-or-delete
        mc--search-backward--repeat-patched
        mc--search-forward
        mc--search-forward--repeat-patched
        mc--test--2
        mc--test-3
        mc/mark-next-lines
        mc/mark-previous-lines
        mouse-set-region
        move-text-up
        pixel-scroll-precision
        pixel-scroll-start-momentum
        previous-buffer
        redraw-display
        save-buffers-kill-terminal
        scroll-bar-toolkit-scroll
        search-forward
        ))
